name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: npm ci

      - name: Test Angular app with GitHub Actions and Karma
        uses: docker://trion/ng-cli-karma:latest
        with:
          args: ng test --watch=false --progress=false

      - name: E2E Test Angular app with GitHub Actions and Protractor
        uses: docker://trion/ng-cli-e2e:latest
        with:
          args: ng e2e

      - name: Deployment auf GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@example.com"
          git checkout -b origin --track origin/gh-pages
          rm -rf !("dist")
          find dist -mindepth 2 -exec mv {} . \;
          rmdir -r dist
          git add .
          git commit -m "updated GitHub Pages"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push --force-with-lease origin gh-pages
