name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository (all branches)
        uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Clean install dependencies
        run: npm ci

      - name: Test Angular app with GitHub Actions and Karma
        uses: docker://trion/ng-cli-karma:latest
        with:
          args: ng test --watch=false --progress=false

      - name: E2E Test Angular app with GitHub Actions and Protractor
        uses: docker://trion/ng-cli-e2e:latest
        with:
          args: ng e2e

      - name: Berechtigungen fixen
        uses: docker://trion/ng-cli-e2e:latest
        with:
          args: chmod -R a+w node_modules

      - name: Deployment auf GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@example.com"
          git checkout gh-pages
          ls | grep -v dist | xargs rm -r
          find dist -mindepth 2 -exec mv {} . \;
          rmdir -r dist
          git add .
          git commit -m "updated GitHub Pages"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push --force-with-lease origin gh-pages
