name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository (all branches)
        uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          mkdir dist
          chmod a+w dist

      - name: Clean install dependencies
        run: |
          npm ci
          chmod -R a+rwx node_modules

      - name: Test Angular app with GitHub Actions and Karma
        uses: docker://trion/ng-cli-karma:latest
        with:
          args: ng test --watch=false --progress=false

      - name: E2E Test Angular app with GitHub Actions and Protractor
        uses: docker://trion/ng-cli-e2e:latest
        with:
          args: ng e2e

      - name: Production build
        uses: docker://trion/ng-cli:latest
        with:
          args: /bin/sh -c "ng build --prod --progress=false --base-href=${GITHUB_REPOSITORY}; rm -rf node_modules"

      - name: Berechtigungen fixen
        uses: docker://trion/ng-cli:latest
        with:
          args: chmod -f -R a+rwx dist

      - name: Deployment auf GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@example.com"
          git checkout gh-pages
          ls | grep -v dist | xargs rm -r
          find dist -mindepth 2 -exec mv {} . \;
          rmdir -r dist
          git add .
          git commit -m "updated GitHub Pages"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push --force-with-lease origin gh-pages
